import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";

const helvetica = localFont({
  src: [
    {
      path: '../../public/fonts/HelveticaNeue-Light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/HelveticaNeue-Roman.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/HelveticaNeue-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/HelveticaNeueBold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/HelveticaNeueCondensedBlack.ttf',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-helvetica',
});


export const metadata: Metadata = {
  title: "Tilottoma Catalogue",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${helvetica.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}